### ISSUE TITLE
FTB Revelations (1.12.2) version 2.0.9b "Preferred" crystal lenses appear to be very wrong. 

### ISSUE THREAD

**Issue by brdagr** [ValkyrieofNight/EnvironmentalTech#116] opened 2018-04-03 20:51 UTC
I am playing the latest FTB Revelations (1.12.2) pack that includes version 2.0.9b of Environmental Tech in it.  
There appears to be a major discrepancy about which materials the void resource miner is getting and what it is supposed to get..

For example, in my resource miner I am getting 100's of blocks of varying types of ice.  The most popular type of ice I am getting is the "Ice Pillar" block which for a Tier 1 resource miner has a 0.92% clear lense drop chance and a 1.65% chance "preferred" (Light Blue) lense drop chance. Okay, now for instance Mica, which is used for speed and accuracy upgrades, has a 0.34% clear lense drop chance and a 2.51% "preferred" (White) lense drop chance again in a Tier 1 resource miner.

In my Tier 1 resource miner, using the Mica preferred lense, the "White" laser lense, I've gotten about 6 blocks over a 2 day period running the miner 24/7 real time. In the same period I've gotten 36 half-stacks (1150+ blocks) of varying types of ice, ALL of which have lower drop % chance even in their PREFERRED lenses, much less the fact that the lense I am using is for Mica which is supposed to have a greater % drop chance than any of the types of ice.

I know this doesn't sound very scientific, but clearly there is an issue with either the JSON weights, or how the mod is handling the specific weights internally.

For the record, before I did any of this, I deleted the void ore and resource miner JSONS in the config folder and let them be regenerated by the mod on startup. Still the same result.

Thank you and have a good day.

**Comment by ValkyrieofNight** [comment] 2018-04-05 06:36
Ahh yes thank you for noticing the bug with the preferred lens. As far as the tons of different ice variants that is a modpack configuration error. The bug with the preferred lenses is fixed and will be in the next release next release :D

**Comment by Meryl** [comment] 2018-04-05 11:43
Thanks! On the subject of the ice, I'm aware that this is caused by a problem with the configuration, but is there any documentation on what exactly the target does to the weight, and what the difference is between OD and OD_PREFIX?

**Comment by ValkyrieofNight** [comment] 2018-04-05 17:50
Yeah the chance is weight / sum_of_all_weights. So OD: will just target the first avaliable entry matching that exact ore name from the Ore Dictionary. OD_PREFIX will take the first avaliable of each entry containing the same prefix from the Ore Dictionary. Example(OD_PREFIX) if you used OD_PREFIX:ore you would get one of each available ore type with the prefix of ore in the Ore Dictionary. So oreTin, oreCopper, oreIron etc. Example(OD) if you used OD:oreTin you would only get the first entry under oreTin added. Hope this makes sense. I will be creating documentation on the loot tables once I re-write the way they are handled to allow more features.

**Comment by grav0r** [comment] 2018-04-09 19:04
does this apply to the void ore miner as well? We play SevTech ages currently, we had 2.08a until yesterday and everything worked fine, except that the server crashed when the pack updated. now we have 2.09c and it doesnt crash any more, but we get like 10x less erodium / kyronite then before..
is this an intended nerf or just a bug? friend has void ore miner t1 with crystal lens, 3 hours 1 erodium, i have with t2 and 4 speed modifiers like 10 in the same time.. i felt before the update the yield was alot higher..

**Closed** 2018-04-26 07:44 UTC
Labels: fixed_next_release
