### ISSUE TITLE
[1.12] solar arrays have a broken tier boost...?

### ISSUE THREAD

**Issue by Paul17041993** [ValkyrieofNight/EnvironmentalTech#59] opened 2017-08-25 10:46 UTC
It seems that the solar arrays get a much higher production boost than what the config defines, from tier 1 to 3 for example you get 12-13 times the power per cell for the same cell tier. If you then had a tier 6 controller maxed out with tier 6 cells, it produces slightly under 10MRF/t, which is pretty over-powered...

Where's the 1.8 figure supposed to be used...?

**Comment by ValkyrieofNight** [comment] 2017-08-25 18:39
Working as intended.

**Comment by ValkyrieofNight** [comment] 2017-08-25 18:57
On second look it might be broken. Thanks for pointing it out.

**Comment by ValkyrieofNight** [comment] 2017-08-25 19:24
Well i've determined that it is working as intended its just I had some old efficiency values overriding the configs ones so that will be fixed in next update.

**Closed by ValkyrieofNight** 2017-08-25 19:24 UTC

**Comment by Paul17041993** [comment] 2017-08-26 06:44
Much better in the latest update, though I still feel the higher tiers are a little far from what their associated miners need, is a tier 6 miner maxed with speed upgrades supposed to use less than 80KRF/t?
