### ISSUE TITLE
[1.12.2]Break and Drop NOTHING

### ISSUE THREAD

**Issue by 5huxiaoyang6** [ValkyrieofNight/EnvironmentalTech#157] opened 2018-10-03 07:35 UTC
ValkyrieLib Version:  2.0.17.1(ingame display.And I'm sure using the latest version download from Curse. )
Environmental Tech Version:2.0.16.1(The same problem as above.The file name seems don't fit the mod's version)
Description of bug:When I broke the  structure frame blocks from the machine with a pick ,I found it drop nothing.And later I tried breaking them with assembler tool,causing the same case.

**Comment by ValkyrieofNight** [comment] 2018-10-03 18:53
Youll need to update Environmental Tech to 2.0.17.1

**Comment by Gamertech** [comment] 2018-10-04 11:15
ValkyrieLib: 2.0.17.2
E-tech: 2.0.17.1
E-mats: 1.0.17.2

Getting the same. Breaking a structure block for example with an assembler or a pick will destroy the block, not drop it.

Downgrading to 2.0.15.1 fixes the issue.

**Comment by ValkyrieofNight** [comment] 2018-10-04 18:08
Ok will try get a fix out tonight.

**Comment by ValkyrieofNight** [comment] 2018-10-04 19:16
Fixed in new release: 2.0.17.3

**Closed** 2018-10-04 19:16 UTC

**Comment by ValkyrieofNight** [comment] 2018-10-04 23:37
That is for ValkyrieLib sorry forgot to mention that haha

**Comment by Gamertech** [comment] 2018-10-05 08:20
Can confirm blocks drop as intended with the new ValkyrieLib. Cheers :)
